server.port=3002

spring.datasource.url=jdbc:sqlite:file::memory:?cache=shared
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.connection-test-query=SELECT 1

spring.sql.init.mode=always
